services:
  - mssql2008r2sp2
environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - sqlcmd -U sa -P Password12! -Q "create database modelar;"
  - npm run init
  - npm test
build: off